version: "3.8"
name: multi-tenant
services:
  multi-tenant-spring:
    build: .
    container_name: multi-tenant-spring
    depends_on: 
      - multi-tenant-keycloak
    restart: on-failure
    ports:
      - 8080:8080

  keycloak:
    enabled: true
    config.resolver: header
    auth-server-url: "http://localhost:8443/"
    realm: job_management
    resource: Job-system-backend
    credentials:
      provider: secret
      secret: egYkqdE5RusA1X6qsjmoghdzyIF6DnTo
#
#    cors: true
#    ssl-required: external
#
#    use-resource-role-mappings: false
#    bearer-only: true
#    autodetect-bearer-only: true
#    security-constraints:
#      - authRoles:
#          - "user"
#        securityCollections:
#          - name: all
#            patterns:
#              - /api/*

  multi-tenant-keycloak:
    image: fhkkelvin/keycloak-multi-tenant-demo
    restart: unless-stopped
    realm: job_management
    container_name: multi-tenant-keycloak
    ports:
      - 8081:8080
