server:
  port: 8000
  servlet:
    context-path: /api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

keycloak:
  realm: carrier
  auth-server-url: http://host.docker.internal:8443/
  ssl-required: external
  resource: web
  bearer-only: true
  credentials:
    secret: 1evtB3OlmMbhyvgvJcv42tuXk9O4On4y
  security-constraints:
    - authRoles:
        - ADMIN
        - USER
      securityCollections:
        - patterns:
            - /tenant/*
          name: tenant management
    - authRoles:
        - MAINTAINER
      securityCollections:
        - patterns:
            - /carrier/*
          name: carrier management

