server:
  port: 8000
  servlet:
    context-path: /api

logging:
  level:
    org:
      keycloak: DEBUG
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

keycloak:
  realm: internal
  auth-server-url: http://host.docker.internal:8443/
  ssl-required: external
  resource: web
  bearer-only: true
  security-constraints:
    - authRoles:
        - USER
        - ADMIN
      securityCollections:
        - patterns:
            - /tenant/*
          name: tenant management
    - authRoles:
        - MAINTAINER
      securityCollections:
        - patterns:
            - /carrier/*
          name: carrier management

