server.port: 8000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

keycloak:
  realm: carrier
  auth-server-url: http://host.docker.internal:8080/
  ssl-required: external
  resource: web
  bearer-only: false
  credentials:
    secret: Wi7C2J6xfYl1WMAt7xnAgenaQkQ2dVmH
  security-constraints:
    - authRoles:
        - ADMIN
        - USER
      securityCollections:
        - patterns:
            - /tenant/*
          name: tenant management
    - authRoles:
        - MAINTAINER
      securityCollections:
        - patterns:
            - /carrier/*
          name: carrier management

